import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "bracelet-rose-quartz",
    name: "Rose Quartz Bracelet",
    category: "Bracelets",
    priceRange: "₹550",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/rose-quartz-bracelet.png",
    benefits: ["Love", "Emotional healing", "Calm energy"],
    chakra: "Heart",
    zodiac: ["Taurus", "Libra"],
  },
  {
    id: "bracelet-amethyst",
    name: "Amethyst Bracelet",
    category: "Bracelets",
    priceRange: "₹599",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/amethyst-bracelet.png",
    benefits: ["Peace", "Protection", "Intuition"],
    chakra: "Third Eye",
    zodiac: ["Aquarius", "Pisces"],
  },
  {
    id: "bracelet-pyrite",
    name: "Pyrite Bracelet",
    category: "Bracelets",
    priceRange: "₹549",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/pyrite-bracelet.png",
    benefits: ["Wealth", "Confidence", "Protection"],
    chakra: "Solar Plexus",
    zodiac: ["Leo"],
  },
  {
    id: "bracelet-citrine",
    name: "Citrine Bracelet",
    category: "Bracelets",
    priceRange: "₹599",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/citrine-bracelet.png",
    benefits: ["Abundance", "Joy", "Success"],
    chakra: "Solar Plexus",
    zodiac: ["Aries", "Gemini", "Leo", "Libra"],
  },
  {
    id: "bracelet-money-magnet",
    name: "Money Magnet Bracelet",
    category: "Bracelets",
    priceRange: "₹699",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/money-magnet-bracelet.png",
    benefits: ["Prosperity", "Luck", "Opportunity"],
    chakra: "Solar Plexus",
    zodiac: ["All"],
  },
  {
    id: "bracelet-red-jasper",
    name: "Red Jasper Bracelet",
    category: "Bracelets",
    priceRange: "₹510",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/red-jasper-bracelet.jpeg",
    benefits: ["Grounding", "Strength", "Stability"],
    chakra: "Root",
    zodiac: ["Aries", "Scorpio"],
  },
  {
    id: "bracelet-seven-chakra",
    name: "7 Chakra Bracelet",
    category: "Bracelets",
    priceRange: "₹599",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/seven-chakra-bracelet.png",
    benefits: ["Balance", "Harmony", "Energy flow"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },
  {
    id: "bracelet-green-aventurine-new",
    name: "Green Aventurine Bracelet",
    category: "Bracelets",
    priceRange: "₹650",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/green-aventurine-bracelet-new.png",
    benefits: ["Luck", "Growth", "Prosperity"],
    chakra: "Heart",
    zodiac: ["Aries", "Leo"],
  },
  {
    id: "ring-pyrite-01",
    name: "Golden Pyrite Prosperity Ring",
    category: "Rings",
    priceRange: "₹3,500 - ₹4,500",
    description:
      "A stunning square-cut Pyrite ring known for attracting wealth, abundance, and protection against negative energy.",
    image: "/images/pyrite-rings.jpeg",
    benefits: ["Attracts wealth", "Blocks negativity", "Boosts willpower"],
    chakra: "Solar Plexus",
    zodiac: ["Leo"],
  },
  {
    id: "ring-turquoise-02",
    name: "Natural Turquoise Healing Ring",
    category: "Rings",
    priceRange: "₹3,800 - ₹5,200",
    description:
      "An authentic oval Turquoise set in silver, perfect for purification, serenity, and protection during travel.",
    image: "/images/turquoise-ring.jpeg",
    benefits: ["Inner calm", "Communication", "Protection"],
    chakra: "Throat",
    zodiac: ["Sagittarius", "Pisces", "Scorpio"],
  },
  {
    id: "bracelet-malachite-01",
    name: "Malachite Protection Bracelet",
    category: "Bracelets",
    priceRange: "₹4,200 - ₹5,600",
    description:
      // fixed: removed generic wording
      "Green Malachite set in a silver chain, chosen for protection and deep emotional healing.",
    image: "/images/malachite-bracelet.jpeg",
    // fixed: replaced generic benefit
    benefits: ["Emotional balance", "Protection", "Growth"],
    chakra: "Heart",
    zodiac: ["Libra", "Scorpio", "Capricorn"],
  },
  {
    id: "bracelet-coral-02",
    name: "Red Coral Vitality Bracelet",
    category: "Bracelets",
    priceRange: "₹4,500 - ₹6,000",
    description: "Vibrant Red Coral set in silver. Stimulates energy, passion, and ambition while overcoming fear.",
    image: "/images/red-coral-bracelet.jpeg",
    benefits: ["Vitality", "Courage", "Motivation"],
    chakra: "Root",
    zodiac: ["Aries", "Scorpio"],
  },
  {
    id: "ring-pearl-03",
    name: "Serene Moonstone Ring",
    category: "Rings",
    priceRange: "₹3,000 - ₹4,100",
    description:
      "A delicate and calming Moonstone/Pearl ring that enhances intuition, promotes inspiration, and brings success in love.",
    image: "/images/pearl-ring.jpeg",
    benefits: ["Intuition", "Emotional balance", "New beginnings"],
    chakra: "Crown",
    zodiac: ["Cancer", "Libra", "Scorpio"],
  },
  {
    id: "bracelet-chakra-set-03",
    name: "Chakra Balance Bracelet Set",
    category: "Bracelets",
    priceRange: "₹2,300 - ₹3,400",
    description:
      "A collection of multi-colored beaded bracelets designed to align your chakras and bring harmony to your energy field.",
    image: "/images/beaded-bracelets.jpeg",
    benefits: ["Balance", "Harmony", "Energy flow"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },
  // Placeholders for other categories to fill the catalog
  {
    id: "pendant-amethyst",
    name: "Amethyst Spirit Pendant",
    category: "Pendants",
    priceRange: "₹2,600 - ₹3,800",
    description: "A raw Amethyst point pendant for spiritual awareness and inner peace.",
    image: "/images/raw-amethyst-pendant.jpg",
    benefits: ["Peace", "Spiritual growth", "Clarity"],
    chakra: "Third Eye",
    zodiac: ["Aquarius", "Pisces"],
  },
  {
    id: "tree-citrine",
    name: "Citrine Abundance Tree",
    category: "Healing Trees",
    priceRange: "₹3,000 - ₹4,500",
    description: "A beautiful wire-wrapped tree with Citrine leaves to invite success and prosperity into your home.",
    image: "/images/citrine-tree.jpg",
    benefits: ["Success", "Abundance", "Optimism"],
    chakra: "Solar Plexus",
    zodiac: ["Aries", "Gemini", "Leo", "Libra"],
  },
  {
    id: "necklace-mixed-chips",
    name: "Multi-Gemstone Chip Necklace",
    category: "Necklaces",
    priceRange: "₹2,600 - ₹3,800",
    description:
      "A vibrant necklace featuring a spectrum of natural gemstone chips including Amethyst, Aventurine, Citrine, and Carnelian.",
    image: "/images/mixed-gem-necklace.jpeg",
    benefits: ["Chakra alignment", "Creativity", "Joy"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },
  {
    id: "bracelet-amethyst-chips",
    name: "Amethyst Chip Bracelet",
    category: "Bracelets",
    priceRange: "₹1,900 - ₹3,000",
    description: "Natural Amethyst chip bracelet for spiritual protection, stress relief, and enhancing intuition.",
    image: "/images/amethyst-chip-bracelet.jpeg",
    benefits: ["Stress relief", "Intuition", "Peace"],
    chakra: "Third Eye",
    zodiac: ["Aquarius", "Pisces"],
  },
  {
    id: "pendant-heart-set",
    name: "Crystal Heart Pendant Collection",
    category: "Pendants",
    priceRange: "₹2,300 - ₹3,400",
    description: "Beautiful heart-shaped pendants available in Rose Quartz, Clear Quartz, Amethyst, and Tigers Eye.",
    image: "/images/heart-pendants-set.jpeg",
    benefits: ["Love", "Clarity", "Protection"],
    chakra: "Heart",
    zodiac: ["Taurus", "Libra", "Leo"],
  },
  {
    id: "bracelet-clear-quartz",
    name: "Clear Quartz Master Healer Bracelet",
    category: "Bracelets",
    priceRange: "₹2,600 - ₹3,800",
    description: "High-quality clear quartz beads known as the 'Master Healer' to amplify energy and thought.",
    image: "/images/clear-quartz-bracelet.jpeg",
    benefits: ["Amplifies energy", "Clarity", "Healing"],
    chakra: "Crown",
    zodiac: ["All"],
  },
  {
    id: "bracelet-pastel-stack",
    name: "Serenity Pastel Bracelet Stack",
    category: "Bracelets",
    priceRange: "₹3,400 - ₹4,900",
    description: "A calming stack of soft pastel gemstone bracelets including Rose Quartz and Blue Lace Agate.",
    image: "/images/stacked-pastel-bracelets.jpeg",
    benefits: ["Calmness", "Emotional healing", "Gentleness"],
    chakra: "Heart",
    zodiac: ["Libra", "Pisces"],
  },
  {
    id: "pendant-amethyst-heart",
    name: "Amethyst Heart Necklace",
    category: "Pendants",
    priceRange: "₹3,000 - ₹4,100",
    description:
      "Deep purple Amethyst heart pendant on a silver chain, perfect for connecting with higher consciousness.",
    image: "/images/amethyst-heart-pendant.jpeg",
    benefits: ["Spiritual connection", "Wisdom", "Protection"],
    chakra: "Crown",
    zodiac: ["Aquarius"],
  },
  {
    id: "bracelet-faceted-gems",
    name: "Faceted Gemstone Brilliance Bracelets",
    category: "Bracelets",
    priceRange: "₹3,000 - ₹4,500",
    description: "Sparkling faceted beads in various stones including Garnet, Lapis Lazuli, and Aventurine.",
    image: "/images/faceted-bead-bracelets.jpeg",
    benefits: ["Energy boost", "Focus", "Confidence"],
    chakra: "Various",
    zodiac: ["All"],
  },
  {
    id: "bracelet-green-aventurine",
    name: "Green Aventurine Luck Bracelet",
    category: "Bracelets",
    priceRange: "₹2,300 - ₹3,400",
    description: "Genuine Green Aventurine beads known as the 'Stone of Opportunity' for luck and prosperity.",
    image: "/images/green-aventurine-bracelet.jpeg",
    benefits: ["Luck", "Opportunity", "Growth"],
    chakra: "Heart",
    zodiac: ["Aries", "Leo"],
  },
  {
    id: "kit-crystal-collection",
    name: "Essential Crystal Collection Kit",
    category: "Crystal Purses",
    priceRange: "₹6,000 - ₹9,000",
    description:
      "A comprehensive set of essential crystals for Love, Protection, Anxiety relief, and Wealth attraction.",
    image: "/images/crystal-guide-shelf.jpeg",
    benefits: ["Complete healing", "Protection", "Abundance"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },
  {
    id: "bracelet-assorted-tray",
    name: "Assorted Healing Gemstone Bracelets",
    category: "Bracelets",
    priceRange: "₹2,600 - ₹3,800",
    description: "A wide variety of smooth round bead bracelets including Dalmatian Jasper, Rose Quartz, and more.",
    image: "/images/mixed-bead-bracelets-tray.jpeg",
    benefits: ["Variety", "Healing", "Style"],
    chakra: "Various",
    zodiac: ["All"],
  },
  {
    id: "bracelet-citrine-golden",
    name: "Golden Healer & Citrine Bracelets",
    category: "Bracelets",
    priceRange: "₹3,400 - ₹4,900",
    description:
      "Radiant golden beads combining the power of Citrine and Golden Healer Quartz for high vibrations and abundance.",
    image: "/images/citrine-bracelets.jpg",
    benefits: ["Abundance", "Healing", "High vibration"],
    chakra: "Solar Plexus",
    zodiac: ["Leo", "Scorpio"],
  },
  {
    id: "stone-selenite-palm",
    name: "Selenite Palm Stone",
    category: "Raw Stones",
    priceRange: "₹1,500 - ₹2,600",
    description:
      "A smooth, polished Selenite palm stone perfect for meditation, clearing negative energy, and bringing mental clarity.",
    image: "/images/selenite-palm-stone.jpg",
    benefits: ["Cleansing", "Clarity", "Peace"],
    chakra: "Crown",
    zodiac: ["Taurus"],
  },
  {
    id: "bag-crystal-beaded",
    name: "Handcrafted Crystal Beaded Clutch",
    category: "Accessories",
    priceRange: "₹6,000 - ₹9,000",
    description:
      "Exquisite handcrafted clutches made with faceted crystal beads. Available in Ruby Red, Sapphire Blue, Rose Pink, and Pearl White.",
    image: "/images/beaded-crystal-bags.jpg",
    benefits: ["Style", "Elegance", "Vibrance"],
    chakra: "Various",
    zodiac: ["All"],
  },
  {
    id: "stone-rose-quartz-hearts",
    name: "Rose Quartz Love Hearts",
    category: "Raw Stones",
    priceRange: "₹1,100 - ₹1,900",
    description:
      "Polished puff hearts made of genuine Rose Quartz. The ultimate symbol of unconditional love and emotional healing.",
    image: "/images/rose-quartz-hearts.jpg",
    benefits: ["Love", "Compassion", "Healing"],
    chakra: "Heart",
    zodiac: ["Taurus", "Libra"],
  },
  {
    id: "stone-green-aventurine-tumbles",
    name: "Green Aventurine Prosperity Stones",
    category: "Raw Stones",
    priceRange: "₹750 - ₹1,500",
    description:
      "Smooth, polished Green Aventurine stones. Carry them in your pocket to attract luck, opportunity, and wealth.",
    image: "/images/green-aventurine-stones.jpg",
    benefits: ["Luck", "Opportunity", "Growth"],
    chakra: "Heart",
    zodiac: ["Virgo", "Libra"],
  },
  {
    id: "bracelet-mixed-chips-stack",
    name: "Chakra Chip Bracelet Stack",
    category: "Bracelets",
    priceRange: "₹1,900 - ₹3,000",
    description:
      "A colorful stack of chip bracelets featuring Amethyst, Rose Quartz, Aventurine, and more for complete energy balance.",
    image: "/images/mixed-chip-bracelet-stack.jpg",
    benefits: ["Balance", "Joy", "Vitality"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },

  {
    id: "bracelet-turquoise-01",
    name: "Turquoise Bracelet",
    category: "Bracelets",
    priceRange: "₹599",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/turquoise-bracelet.png",
    benefits: ["Inner calm", "Communication", "Protection"],
    chakra: "Throat",
    zodiac: ["Sagittarius", "Pisces", "Scorpio"],
  },
  {
    id: "bracelet-carnelian-01",
    name: "Carnelian Bracelet",
    category: "Bracelets",
    priceRange: "₹499",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/carnelian-bracelet.jpeg",
    benefits: ["Courage", "Energy and vitality", "Motivation"],
    chakra: "Sacral",
    zodiac: ["Aries", "Leo", "Capricorn"],
  },
  {
    id: "bracelet-tiger-eye-01",
    name: "Tiger Eye Bracelet",
    category: "Bracelets",
    priceRange: "₹510",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/tiger-eye-bracelet.png",
    benefits: ["Focus and clarity", "Confidence", "Protection"],
    chakra: "Solar Plexus",
    zodiac: ["All"],
  },
  {
    id: "bracelet-opalite-01",
    name: "Opalite Bracelet",
    category: "Bracelets",
    priceRange: "₹499",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/opalite-bracelet.png",
    benefits: ["Emotional healing", "Calming energy", "Clarity"],
    chakra: "Heart",
    zodiac: ["Cancer", "Libra", "Pisces"],
  },
  {
    id: "bracelet-hematite-01",
    name: "Hematite Bracelet",
    category: "Bracelets",
    priceRange: "₹550",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/hematite-bracelet.png",
    benefits: ["Grounding", "Energy protection", "Stability"],
    chakra: "Root",
    zodiac: ["Aries", "Scorpio"],
  },
  {
    id: "bracelet-blue-tiger-eye-01",
    name: "Blue Tiger Eye Bracelet",
    category: "Bracelets",
    priceRange: "₹750",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/blue-tiger-eye-bracelet.png",
    benefits: ["Peace of mind", "Focus and clarity", "Emotional balance"],
    chakra: "Throat",
    zodiac: ["Gemini", "Libra", "Sagittarius"],
  },

  {
    id: "tree-rose-quartz-01",
    name: "Rose Quartz Tree",
    category: "Healing Trees",
    priceRange: "₹799",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/rose-quartz-tree.jpg",
    benefits: ["Love and relationships", "Emotional healing", "Calm energy"],
    chakra: "Heart",
    zodiac: ["Taurus", "Libra"],
  },
  {
    id: "tree-amethyst-01",
    name: "Amethyst Tree",
    category: "Healing Trees",
    priceRange: "₹850",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/amethyst-tree.png",
    benefits: ["Peace of mind", "Spiritual growth", "Clarity"],
    chakra: "Third Eye",
    zodiac: ["Aquarius", "Pisces"],
  },
  {
    id: "tree-seven-chakra-01",
    name: "7 Chakra Tree",
    category: "Healing Trees",
    priceRange: "₹799",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/seven-chakra-tree.jpg",
    benefits: ["Balance and positivity", "Energy and motivation", "Harmony"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },
  {
    id: "tree-opal-01",
    name: "Opal Tree",
    category: "Healing Trees",
    priceRange: "₹799",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/opal-tree.jpg",
    benefits: ["Spiritual growth", "Emotional healing", "Balance and positivity"],
    chakra: "Crown",
    zodiac: ["All"],
  },

  {
    id: "necklace-seven-chakra-chip-01",
    name: "7 Chakra Chip Necklace",
    category: "Necklaces",
    priceRange: "₹499",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/seven-chakra-chip-necklace.png",
    benefits: ["Balance and positivity", "Energy flow", "Harmony"],
    chakra: "All Chakras",
    zodiac: ["All"],
  },

  {
    id: "pendant-rose-quartz-01",
    name: "Rose Quartz Pendant",
    category: "Pendants",
    priceRange: "₹450",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/rose-quartz-pendant.png",
    benefits: ["Love and relationships", "Emotional healing", "Calm energy"],
    chakra: "Heart",
    zodiac: ["Taurus", "Libra"],
  },
  {
    id: "pendant-amethyst-01",
    name: "Amethyst Pendant",
    category: "Pendants",
    priceRange: "₹450",
    description: "High-quality natural crystal product with healing properties.",
    image: "/images/amethyst-pendant-new.png",
    benefits: ["Spiritual growth", "Peace of mind", "Clarity"],
    chakra: "Third Eye",
    zodiac: ["Aquarius", "Pisces"],
  },
]

export const categories = [
  "All",
  "Bracelets",
  "Rings",
  "Pendants",
  "Necklaces",
  "Malas",
  "Healing Trees",
  "Crystal Purses",
  "Raw Stones",
  "Accessories",
]
